[2024-11-18T08:42:55.603+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid19_data_pipeline.save_data_into_db manual__2024-11-18T08:42:52.475331+00:00 [queued]>
[2024-11-18T08:42:55.624+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid19_data_pipeline.save_data_into_db manual__2024-11-18T08:42:52.475331+00:00 [queued]>
[2024-11-18T08:42:55.625+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-18T08:42:55.659+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): save_data_into_db> on 2024-11-18 08:42:52.475331+00:00
[2024-11-18T08:42:55.666+0000] {standard_task_runner.py:60} INFO - Started process 31082 to run task
[2024-11-18T08:42:55.673+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'covid19_data_pipeline', 'save_data_into_db', 'manual__2024-11-18T08:42:52.475331+00:00', '--job-id', '10270', '--raw', '--subdir', 'DAGS_FOLDER/covid19_data_pipeline.py', '--cfg-path', '/tmp/tmp7vgud9p6']
[2024-11-18T08:42:55.675+0000] {standard_task_runner.py:88} INFO - Job 10270: Subtask save_data_into_db
[2024-11-18T08:42:55.847+0000] {task_command.py:423} INFO - Running <TaskInstance: covid19_data_pipeline.save_data_into_db manual__2024-11-18T08:42:52.475331+00:00 [running]> on host 3c704ad499e6
[2024-11-18T08:42:55.977+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid19_data_pipeline' AIRFLOW_CTX_TASK_ID='save_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T08:42:52.475331+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T08:42:52.475331+00:00'
[2024-11-18T08:42:56.018+0000] {base.py:83} INFO - Using connection ID 'azure_postgres_conn' for task execution.
[2024-11-18T08:42:56.070+0000] {sql.py:457} INFO - Running statement: 
        INSERT INTO phawatmk.weekly_covid19_reports (
            year, weeknum, new_case, total_case, new_case_excludeabroad,
            total_case_excludeabroad, new_recovered, total_recovered,
            new_death, total_death, case_foreign, case_prison,
            case_walkin, case_new_prev, case_new_diff, death_new_prev,
            death_new_diff, update_date
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
    , parameters: (2024, 45, 0, 41711, 0, 41711, 0, 0, 0, 214, None, None, None, 0, 0, 0, 0, '2023-05-21 11:53:27')
[2024-11-18T08:42:56.075+0000] {sql.py:466} INFO - Rows affected: 1
[2024-11-18T08:42:56.080+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-11-18T08:42:56.096+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=covid19_data_pipeline, task_id=save_data_into_db, execution_date=20241118T084252, start_date=20241118T084255, end_date=20241118T084256
[2024-11-18T08:42:56.144+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-18T08:42:56.163+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-11-18T08:42:56.188+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
