[2024-11-19T00:00:02.590+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid19_data_pipeline.save_data_into_db scheduled__2024-11-18T00:00:00+00:00 [queued]>
[2024-11-19T00:00:02.598+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid19_data_pipeline.save_data_into_db scheduled__2024-11-18T00:00:00+00:00 [queued]>
[2024-11-19T00:00:02.598+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-19T00:00:02.611+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): save_data_into_db> on 2024-11-18 00:00:00+00:00
[2024-11-19T00:00:02.615+0000] {standard_task_runner.py:60} INFO - Started process 47771 to run task
[2024-11-19T00:00:02.620+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'covid19_data_pipeline', 'save_data_into_db', 'scheduled__2024-11-18T00:00:00+00:00', '--job-id', '11639', '--raw', '--subdir', 'DAGS_FOLDER/covid19_data_pipeline.py', '--cfg-path', '/tmp/tmpshl19jrs']
[2024-11-19T00:00:02.621+0000] {standard_task_runner.py:88} INFO - Job 11639: Subtask save_data_into_db
[2024-11-19T00:00:02.674+0000] {task_command.py:423} INFO - Running <TaskInstance: covid19_data_pipeline.save_data_into_db scheduled__2024-11-18T00:00:00+00:00 [running]> on host 3c704ad499e6
[2024-11-19T00:00:02.763+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid19_data_pipeline' AIRFLOW_CTX_TASK_ID='save_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-18T00:00:00+00:00'
[2024-11-19T00:00:02.785+0000] {base.py:83} INFO - Using connection ID 'azure_postgres_conn' for task execution.
[2024-11-19T00:00:02.845+0000] {sql.py:457} INFO - Running statement: 
        INSERT INTO phawatmk.weekly_covid19_reports (
            year, weeknum, new_case, total_case, new_case_excludeabroad,
            total_case_excludeabroad, new_recovered, total_recovered,
            new_death, total_death, case_foreign, case_prison,
            case_walkin, case_new_prev, case_new_diff, death_new_prev,
            death_new_diff, update_date
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
    , parameters: (2024, 45, 504, 42215, 504, 42215, 0, 0, 1, 215, 0, 0, 504, 0, 504, 0, 1, '2024-11-18 15:39:15')
[2024-11-19T00:00:02.848+0000] {sql.py:466} INFO - Rows affected: 1
[2024-11-19T00:00:02.928+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-11-19T00:00:02.938+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=covid19_data_pipeline, task_id=save_data_into_db, execution_date=20241118T000000, start_date=20241119T000002, end_date=20241119T000002
[2024-11-19T00:00:02.992+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-19T00:00:03.003+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-11-19T00:00:03.014+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
